### ISSUE TITLE
NET CORE 3.0 MONO 6.4.0 

### ISSUE THREAD

**Issue by naughtyGitCat** [MicrosoftDocs/xamarin-docs.zh-cn#56]
the Resources folder and then the layout folder does not contain Main.axml, only have activity_main.xml and content_main.xml

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android：快速入门 - Xamarin](https://docs.microsoft.com/zh-CN/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=macos#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by srvbpigh** [comment]
Hello, @naughtyGitCat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @naughtyGitCat

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/2257

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
