### ISSUE TITLE
Shell.NavBarIsVisible="False"  is not work 

### ISSUE THREAD

**Issue by wa926talent** [MicrosoftDocs/xamarin-docs.zh-cn#58]
[在此处输入反馈]
Shell.NavBarIsVisible="False"  is not work 
Xamarin.Forms  4.3.0.947036
Android 9.0
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c9d653fd-51ed-ed03-db65-a9efb684dc12
* Version Independent ID: 06470094-10f9-b28e-4ece-4da457a4a609
* Content: [Xamarin.Forms Shell 页面配置 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/app-fundamentals/shell/configuration)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/configuration.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/xamarin-forms/app-fundamentals/shell/configuration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @wa926talent
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2304](https://github.com/MicrosoftDocs/xamarin-docs/issues/2304) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @wa926talent 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/2304

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
