### ISSUE TITLE
Document markdown formatting syntax wrong

### ISSUE THREAD

**Issue by inascf** [MicrosoftDocs/xamarin-docs.zh-cn#7]
``` 
![拖放 framework]Images/hello-from-csharp-ios-drag-drop-framework.png)
```
miss a "("

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e624548b-1611-c17b-0984-1344c7585ffc
* Version Independent ID: 684e167e-49fd-3f06-9a9c-1ee253635086
* Content: [IOS 入门 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/tools/dotnet-embedding/get-started/objective-c/ios)
* Content Source: [docs/tools/dotnet-embedding/get-started/objective-c/ios.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/tools/dotnet-embedding/get-started/objective-c/ios.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by inascf** [comment]
```
![拖放 framework](ios-images/hello-from-csharp-ios-drag-drop-framework.png)
```  
 maybe is right

**Comment by CeciAc** [comment]
Hello, @inascf ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/xamarin-docs/issues/637.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
